package gui;
import javax.swing.*;
import java.awt.*;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

// frame di registrazione,
public class RegisterGUI {
    private JTextField usernameJTextField;
    private JPasswordField passwordJPasswordField;
    private JButton registerJButton;
    private JPanel registerPanel;
    private JFrame registerJFrame;

    // client da registrare
    public RegisterGUI(ClientGUI client) {
        registerJFrame = new JFrame("Quizzle");
        registerJFrame.setContentPane(registerPanel);
        registerJFrame.pack();
        registerJFrame.setVisible(true);
        registerJFrame.setResizable(false);

        registerJButton.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                super.mouseClicked(e);
                // username e password inseriti nei textField
                String username = usernameJTextField.getText();
                String password = new String(passwordJPasswordField.getPassword());
                String fromServer = client.register(username, password);
                // registrato
                if (fromServer.endsWith("successo")) {
                    // chiudo il frame di regisreazione
                    JOptionPane.showMessageDialog(new JFrame(), fromServer, "Registrato", JOptionPane.INFORMATION_MESSAGE);
                    close();

                    // non registrato
                } else {
                    JOptionPane.showMessageDialog(new JFrame(), fromServer, "Non registrato", JOptionPane.ERROR_MESSAGE);
                }
            }
        });
    }

    public void close() {
        registerJFrame.setVisible(false);
        registerJFrame.dispose();
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        registerPanel = new JPanel();
        registerPanel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(3, 4, new Insets(0, 0, 0, 0), -1, -1));
        registerPanel.setBorder(BorderFactory.createTitledBorder("Registrazione utente"));
        final JLabel label1 = new JLabel();
        label1.setText("Nome utente");
        registerPanel.add(label1, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 2, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label2 = new JLabel();
        label2.setText("Password");
        registerPanel.add(label2, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        usernameJTextField = new JTextField();
        registerPanel.add(usernameJTextField, new com.intellij.uiDesigner.core.GridConstraints(0, 2, 1, 2, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(100, -1), null, 0, false));
        passwordJPasswordField = new JPasswordField();
        registerPanel.add(passwordJPasswordField, new com.intellij.uiDesigner.core.GridConstraints(1, 2, 1, 2, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(100, -1), null, 0, false));
        registerJButton = new JButton();
        registerJButton.setText("Registrati");
        registerPanel.add(registerJButton, new com.intellij.uiDesigner.core.GridConstraints(2, 2, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return registerPanel;
    }
}